services:

  # https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html

  kafka: 
    image: confluentinc/cp-kafka:7.6.1 
    restart: always 
    ports: 
      - "29092:29092" 
      - "9092:9092" 
    volumes: 
      - kafka_data:/var/lib/kafka/data 
    environment: 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 
      KAFKA_NODE_ID: 1 
      CLUSTER_ID: 8GyRIS62T8aMSkDJs-AH5Q 
      KAFKA_PROCESS_ROLES: controller,broker 
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:9093 
    healthcheck: 
      test: kafka-topics --bootstrap-server localhost:9092 --list 
      interval: 10s 
      timeout: 5s 
      start_period: 30s 
      retries: 5 
  
# https://docs.confluent.io/platform/current/schema-registry/installation/config.html

#  schema-registry:
#    image: confluentinc/cp-schema-registry:latest
#    hostname: schema-registry
#    container_name: schema-registry
#    ports:
#      - "8085:8085"
#    depends_on:
#      - broker-1
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
#      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker-1:9092
#      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas

  # https://docs.kafka-ui.provectus.io/configuration/configuration-file

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8088:8080
    # depends_on:
    #   - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
#      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8085
      DYNAMIC_CONFIG_ENABLED: 'true'

volumes: 
  kafka_data:
