server:
  port: 8181
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5450/mt_core_transfers?minimumIdle=2
    username: postgres
    password: postgres
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    producer:
      properties:
        allow.auto.create.topics: false
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: '*'
integrations:
  limits:
    url: http://localhost:8182/api/v1/limits
    read-timeout: 30s
    connect-timeout: 2s
  other:
    url: http://localhost:8185/api/v1/other
    read-timeout: 40s
    connect-timeout: 3s