server:
  port: 8080
spring:
  application:
    name: mt-core-transfers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mt_core_transfers
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        allow.auto.create.topics: false
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

transfers:
  max-transfer-sum: 100.00
  demo-transfers-enabled: false
  blocked-account-numbers:
    - "123"
    - "234"
    - "456"
  topic: local.otus-kafka.transfers
integrations:
  limits:
    url: http://localhost:8080/api/v1/limits
    read-timeout: 30s
    write-timeout: 2s
logging:
  level:
    org.zalando.logbook.Logbook: TRACE


